### ISSUE TITLE
Unable to be used with Carthage

### ISSUE THREAD

**Issue by solidcell** [Leanplum/Leanplum-iOS-SDK#5] opened 2015-09-21 20:44 UTC
I'm running into the following issue when using Leanplum with Carthage:

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in Leanplum(LPRevenueManager.o)
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in Leanplum(LPRevenueManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It looks as though it's not being linked to `StoreKit`.

**Comment by afirst** [comment] 2015-09-22 04:38
Hi, can you confirm which version of the SDK are you using? The current Podspec contains a weak reference to the StoreKit framework.

**Comment by solidcell** [comment] 2015-09-22 18:23
I'm using `1.3.8.1` with Xcode 6.4.

I could be mistaken, but I don't believe Carthage makes any use of the Podspec.

I can't verify this, since you only expose the build framework, but it might be that you aren't linking to StoreKit under "Link Binary with Libraries".  Just a guess.

I managed to get it further by linking to StoreKit myself in the main app, however it runs into a Carthage error when running the `copy-frameworks` build phase command:
```
Failed to read file or folder at /Users/solidcell/Library/Developer/Xcode/DerivedData/myProject/Build/Products/Development-iphonesimulator/MyApp.app/Frameworks/Leanplum.framework
```
This looks to be the error: https://github.com/Carthage/Carthage/blob/3c5580749930c7b505638f7aca2c5c3f2cb2efb9/Source/CarthageKit/Errors.swift#L159

I'll look into it further, but it would be helpful if you could try building and archiving your source with Carthage to see if it produces a pre-built framework that Carthage can read: https://github.com/Carthage/Carthage/blob/master/README.md#archive-prebuilt-frameworks-into-one-zip-file
I'm not sure what about your provided framework it's having a problem reading.

**Comment by solidcell** [comment] 2015-09-30 22:36
I'm seeing this issue with Xcode 7.0.1 as well.

**Comment by shrishabhatrzt** [comment] 2015-10-25 10:49
I am facing the same thing. Any solution yet?

**Comment by danielphillips** [comment] 2015-11-10 10:08
Please add support for Carthage.

**Comment by justin** [comment] 2016-10-04 16:47
Would like to nudge this.

**Comment by afirst** [comment] 2016-10-04 16:56
Have you tried with the latest SDK? Version 1.4.0 and above uses a dynamic framework, so that should be supported by Carthage.

**Comment by justin** [comment] 2016-10-04 17:00
Yeah. We tried it while testing our integration.

I think the problem is that the zip file you put under your Releases on Github also includes the podspec file inside of it, instead of just the `.framework` file which causes Carthage to get confused and not copy the framework into the `Carthage/Builds/iOS` folder.

**Comment by benmarten** [comment] 2016-10-05 20:10
Not sure if Carthage is able to ignore the .podspec file somehow?

Possible workarounds:
- Create a new tag specifically for carthage builds, e.g. `1.4.0-carthage`, which is created from another branch that only contains the `.frameworks` folder.
- Create a new repo for carthage users, this would possibly take a little more time as we have to include carthage in our release process.

Let me know if you have any other suggestions, or I can suggest providing first suggestion soon...

**Comment by justin** [comment] 2016-10-05 21:17
All you really need to do is add a zip file with the framework to your releases in Github and it works. I just tested it on this fork here: https://github.com/justin/Leanplum-iOS-SDK/releases/tag/1.4.0.2.1

```
~/Leanplum-iOS-SDK
zip -r Leanplum.framework.zip Leanplum.framework
[Upload however you want to Github]
```

No extra repo or extra tags needed.

**Comment by benmarten** [comment] 2016-10-06 04:37
Great, thanks for the example. I've uploaded it manually for now. Will update our release scripts to include this automatically for the next release, e.g. http://stackoverflow.com/a/5207352/2302437

**Comment by benmarten** [comment] 2016-11-10 22:30
We've included this in our release scripts. All upcoming releases will have the zip file attached. Closing, feel free to reopen if there's anything else ;)

**Closed by benmarten** 2016-11-10 22:30 UTC
Labels: enhancement
