### ISSUE TITLE
LPVar with default BOOL value issue

### ISSUE THREAD

**Issue by rpassis** [Leanplum/Leanplum-iOS-SDK#94] opened 2017-10-27 01:11 UTC
Hi guys,

Not sure if I'm doing something wrong but if I setup a `LPVar` with a default `Boolean` value:

`fileprivate var lpVarForTrueOrFalse = LPVar.define("lpVarForTrueOrFalse", with: true)`

...and then observe for value changes with the callback below, when the call fails for whatever reason (i.e. no internet), the callback is called immediately but there is no indication that it failed and when I inspect the `LPVar` value it returns false when it should actually be `nil`.

```
lpVarForTrueOrFalse?.onValueChanged { [weak self] in
    print(lpVarForTrueOrFalse?.boolValue()) // Returns false instead of nil    
}
```

I think I understand why this happens as the SDK is built in Objective-C, but perhaps it might be a good idea to provide an API where the callback also includes a `success` flag? 

```
lpVarForTrueOrFalse?.onValueChanged { [weak self] success in
    if success == false {  // LPVar was not updated for whatever reason
        print(lpVarForTrueOrFalse?.defaultValue()
    } else {
        print(lpVarForTrueOrFalse?.boolValue())
    }
}
```

This is so we can check and choose to use our fallback default value if the call to get update values from Leanplum has failed.

At the moment I have no way of knowing that this happened and since `boolValue()` always returns a value I have no way of knowing whether that's what the server returned or if it's because we haven't been able to fetch the values.

An easy workaround for now is to work with strings since `stringValue()` will return nil if the call to Leanplum fails.

Hope that all makes sense but let me know if you need need any more info?
Cheers,
Rog

**Comment by alexisoyama** [comment] 2017-11-11 23:19
TSE should be handling this. Please close it if the issue is resolved.

**Closed** 2017-11-12 00:19 UTC
