### ISSUE TITLE
Please add a Carthage Binary Project Specification

### ISSUE THREAD

**Issue by st3fan** [Leanplum/Leanplum-iOS-SDK#65] opened 2017-08-25 16:51 UTC
This will allow us to properly import the binary release.

The format is specified at https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification - it is a simple JSON file that just needs a version to .zip file mapping.

**Comment by benmarten** [comment] 2017-08-29 13:45
I see. Is the issue that you are describing that using:

```
github "Leanplum/Leanplum-iOS-SDK"
```

In your pod file would lead to the actual source to be cloned right?

**Comment by benmarten** [comment] 2017-08-29 21:24
https://leanplum.atlassian.net/browse/LP-5761

**Comment by st3fan** [comment] 2017-09-07 00:59
Yes. But we want to replace that with a `binary` reference instead. That looks like this:

```
binary "https://my.domain.com/release/MyFramework.json"
```

An example of the `.json` file can be found at https://github.com/mozilla-mobile/firefox-ios/blob/master/Leanplum.json - it simply points to your release `.zip` files, organized by version number.

We put that file in our repo, but it would be good if you guys could host it and maintain it somewhere.

**Comment by milos1290** [comment] 2017-09-08 08:30
@st3fan I'm not sure what is the difference. Are you unable to use prebuilt binaries with carthage ?
If so, i'm not able to reproduce your issue, adding `github "Leanplum/Leanplum-iOS-SDK"` to a Cartfile will download latest prebuilt .framework directly from github releases.

**Comment by alexisoyama** [comment] 2017-09-14 19:45
Closing this because we are not able to identify the issue. 
If we are missing something, please re-open this with more details.

**Closed by alexisoyama** 2017-09-14 19:45 UTC

**Comment by st3fan** [comment] 2017-09-18 12:18
@alexisoyama @milos1290 The problem is that we are in a situation where we have to run Carthage with `--no-binaries` because since the switch to Swift 3.2, most binaries are invalid.  For example without `--no-binaries` we get an Alamofire framework that is compiled against Swift 3.1 and thus cannot be used now in Xcode 9 / Swift 3.2 project.

The solution is simple for us, we run Carthage with `--no-binaries` - but .. of course that rules out Leanplum. Since Leanplum cannot be build from source by Carthage.

Putting up a `Leanplum.json` solves this problem. We can run with `--no-binaries` and still make an exception for Leanplum.

*The real solution here is of course to make Leanplum an actual proper Carthage dependency - that compiles from source.*

**Comment by alexisoyama** [comment] 2017-09-18 20:29
@st3fan We will investigate more about Carthage. But it seem like you only need a json file where we update it regularly with releases. We can totally do this. Any filename in our repo will do? Ex. Carthage.json

**Comment by milos1290** [comment] 2017-09-18 22:06
@st3fan If Alamofire is the only one that is making you a problem, may i suggest using this
bumping it to 4.5.1 which officially supports XCode 9 and Swift 3.2 and remove `--no-binaries` flag ?

**Comment by st3fan** [comment] 2017-09-18 23:52
Yes, but the probem is not Alamofire, the problem is Leanplum :-) Unfortunately newer versions have breaking APIs and sometimes we are just not ready to include that.

**Comment by milos1290** [comment] 2017-09-19 12:24
@st3fan I totally understand. We will definitely add json spec which points to out release.

**Comment by benmarten** [comment] 2017-09-20 17:38
What if clients want to explicitly use `--no-binaries` to include the sources? When we would add that .json file, wouldn't that defeat the purpose of the flag?

**Comment by st3fan** [comment] 2017-09-25 19:38
@benmarten I am not sure, but adding `--no-binaries` should result in a proper compilation from source for Leanplum. I don't think that is possible currently. I don't think it actually pulls in Leanplum at all with `--no-binries`. Or it does and then fails to compile.
